version: '3'
services:
  web:
    build:
      context: .
    working_dir: /myapp
    command: gulp watch
    volumes:
      - .:/myapp
      - /myapp/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - datavolume:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: we-cycling
      MYSQL_PASSWORD: we-password
      MYSQL_DATABASE: we-cycling
    ports:
      - "3306:3306"

volumes:
  datavolume:
